name: CI/CD

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/test-image:latest .

      - name: Run Docker Image
        run: docker run -d -p 80:80 --name active-container ${{ secrets.DOCKER_USERNAME }}/test-image:latest

      - name: Run Liatrio's Unit tests
        uses: liatrio/github-actions/apprentice-action@808117af9b4a1e57c4cb79dbcb2d25de5ea3c68d

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/test-image:latest

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws 
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Pull Image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/test-image:latest
      
      - name: Tag for ECR
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/test-image:latest public.ecr.aws/b2i0s2v3/liatrio_interview_exercise_ecr_repo:latest

      - name: Push to ECR
        run: docker push public.ecr.aws/b2i0s2v3/liatrio_interview_exercise_ecr_repo:latest
          
    



    
      



    
